def get_feature_configs():
    """Gets all the supported ABCD features
    Returns:
    feature_configs: list of feature configurations
    """
    feature_configs = [
        {
            "id": "a_dynamic_start",
            "name": "Dynamic Start",
            "category": "Attract",
            "criteria": "The first shot in the video changes in less than 3 seconds.",
            "type": "first_5_secs_video",
            "question": "Does the first shot in the video change in less than 3 seconds?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}.",
                "Query the extracted video data using the provided tools to answer the question.",
                "Provide the exact timestamp when the first shot in the video changes.",
                "Return True if and only if the first shot in the video changes in less than 3 seconds.",
            ],
            "mode": "baseline",
            "tool_group": None,
        },
        {
            "id": "a_quick_pacing",
            "name": "Quick Pacing",
            "category": "Attract",
            "criteria": "Within ANY 5 consecutive seconds there are 5 or more shots in the video. These include hard cuts, soft transitions and camera changes such as camera pans, swipes, zooms, depth of field changes, tracking shots and movement of the camera.",
            "type": "full_video",
            "question": "Are there 5 or more shots within ANY 5 consecutive seconds in the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Query the extracted video data using the provided tools to answer the question.",
                "Provide the shot changes count in the following format: Number of shots: #",
                "Provide the exact timestamp when the shot changes happen and a description of the shot.",
                "Return False if and only if the number of identified shots is less than 5.",
            ],
            "mode": "baseline",
            "tool_group": None,
        },
        {
            "id": "a_quick_pacing_1st_secs",
            "category": "Attract",
            "name": "Quick Pacing (First 5 seconds)",
            "criteria": "There are at least 5 shot changes or visual cuts detected in the video. These include hard cuts, soft transitions and camera changes such as camera pans, swipes, zooms, depth of field changes, tracking shots and movement of the camera.",
            "type": "first_5_secs_video",
            "question": "Are there at least 5 shot changes or visual cuts detected in the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Query the extracted video data using the provided tools to answer the question.",
                "Provide the shot changes count in the following format: Number of shots: #",
                "Provide the exact timestamp when the shot changes happen and a description of the shot.",
                "Return False if the number of shots identified is less than 5.",
            ],
            "mode": "baseline",
            "tool_group": None,
        },
        {
            "id": "a_supers",
            "name": "Supers",
            "category": "Attract",
            "criteria": "Any supers (text overlays) have been incorporated at any time in the video.",
            "type": "full_video",
            "question": "Are there any supers (text overlays) at any time in the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Query the extracted video data using the provided tools to answer the question.",
                "Provide the exact timestamp where supers are found as well as the list of supers.",
            ],
            "mode": "baseline",
            "tool_group": None,
        },
        {
            "id": "a_supers_with_audio",
            "name": "Supers with Audio",
            "category": "Attract",
            "criteria": "The speech heard in the audio of the video matches OR is contextually supportive of the overlaid text shown on screen.",
            "type": "full_video",
            "question": "Does the speech match any supers (text overlays) in the video or is the speech contextually supportive of the overlaid text shown on the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Query the extracted video data using the provided tools to answer the question.",
                "Provide the exact timestamp where supers are found and the timestamp when the speech matches the supers or is contextually supportive of the overlaid text shown on the video.",
            ],
            "mode": "agentic",
            "tool_group": "audio_text",
        },
        {
            "id": "b_brand_mention_speech",
            "name": "Brand Mention (Speech)",
            "category": "Brand",
            "criteria": "The brand name is heard in the audio or speech at any time in the video.",
            "type": "full_video",
            "question": "Does the speech mention the brand {brand_name} at any time in the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Provide the exact timestamp when the brand {brand_name} is heard in the speech of the video.",
            ],
            "mode": "agentic",
            "tool_group": "audio",
        },
        {
            "id": "b_brand_mention_speech_1st_5_secs",
            "name": "Brand Mention (Speech) (First 5 seconds)",
            "category": "Brand",
            "criteria": "The brand name is heard in the audio or speech in the first 5 seconds of the video.",
            "type": "first_5_secs_video",
            "question": "Does the speech mention the brand {brand_name} in the first 5 seconds of the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "IMPORTANT: Only analyse audio data from the first 5 seconds of the video.",
                "Provide the exact timestamp when the brand {brand_name} is heard in the speech.",
                "Return True if and only if the brand {brand_name} is heard in the first 5 seconds.",
            ],
            "mode": "agentic",
            "tool_group": "audio",
        },
        {
            "id": "b_brand_visuals",
            "name": "Brand Visuals",
            "category": "Brand",
            "criteria": "Branding, defined as the brand name or brand logo are shown in-situation or overlaid at any time in the video.",
            "type": "full_video",
            "question": "Is the brand {brand_name} or brand logo {brand_name} visible at any time in the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Query the extracted video data using the provided tools to answer the question.",
                "Provide the exact timestamp when the brand {brand_name} or brand logo {brand_name} is found.",
            ],
            "mode": "agentic",
            "tool_group": "visual_text",
        },
        {
            "id": "b_brand_visuals_1st_5_secs",
            "name": "Brand Visuals (First 5 seconds)",
            "category": "Brand",
            "criteria": "Branding, defined as the brand name or brand logo are shown in-situation or overlaid in the first 5 seconds of the video.",
            "type": "first_5_secs_video",
            "question": "Is the brand {brand_name} or brand logo {brand_name} visible in the first 5 seconds of the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "IMPORTANT: Only analyse data from the first 5 seconds of the video.",
                "Provide the exact timestamp when the brand {brand_name} or brand logo {brand_name} is found.",
            ],
            "mode": "agentic",
            "tool_group": "visual_text",
        },
        {
            "id": "b_product_mention_speech",
            "name": "Product Mention (Speech)",
            "category": "Brand",
            "criteria": "The branded product names or generic product categories are heard or mentioned in the audio or speech at any time in the video.",
            "type": "full_video",
            "question": "Are any of the following products: {branded_products} or product categories: {branded_products_categories} heard at any time in the speech of the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Provide the exact timestamp when the products {branded_products} or product categories {branded_products_categories} are heard in the speech of the video.",
                "Return False if the products or product categories are not heard in the speech.",
                "Only strictly use the speech of the video to answer, don't consider visual elements.",
            ],
            "mode": "agentic",
            "tool_group": "audio",
        },
        {
            "id": "b_product_mention_speech_1st_5_secs",
            "name": "Product Mention (Speech) (First 5 seconds)",
            "category": "Brand",
            "criteria": "The branded product names or generic product categories are heard or mentioned in the audio or speech in the first 5 seconds of the video.",
            "type": "first_5_secs_video",
            "question": "Are any of the following products: {branded_products} or product categories: {branded_products_categories} heard in the speech in the first 5 seconds of the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "IMPORTANT: Only analyse audio data from the first 5 seconds of the video.",
                "Provide the exact timestamp when the products {branded_products} or product categories {branded_products_categories} are heard in the speech.",
                "Return False if the products or product categories are not heard in the speech.",
                "Only strictly use the speech of the video to answer, don't consider visual elements.",
            ],
            "mode": "agentic",
            "tool_group": "audio",
        },
        {
            "id": "b_product_mention_text",
            "name": "Product Mention (Text)",
            "category": "Brand",
            "criteria": "The branded product names or generic product categories are present in any text or overlay at any time in the video.",
            "type": "full_video",
            "question": "Is any of the following products: {branded_products} or product categories: {branded_products_categories} present in any text or overlay at any time in the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Provide the exact timestamp when the products {branded_products} or product categories: {branded_products_categories} are found  in any text or overlay in the video.",
            ],
            "mode": "agentic",
            "tool_group": "text",
        },
        {
            "id": "b_product_mention_text_1st_5_secs",
            "name": "Product Mention (Text) (First 5 seconds)",
            "category": "Brand",
            "criteria": "The branded product names or generic product categories are present in any text or overlay in the first 5 seconds of the video.",
            "type": "first_5_secs_video",
            "question": "Is any of the following products: {branded_products} or product categories: {branded_products_categories} present in any text or overlay in the first 5 seconds of the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "IMPORTANT: Only analyse text data from the first 5 seconds of the video.",
                "Provide the exact timestamp when the products {branded_products} or product categories: {branded_products_categories} are found in any text or overlay.",
            ],
            "mode": "agentic",
            "tool_group": "text",
        },
        {
            "id": "b_product_visuals",
            "name": "Product Visuals",
            "category": "Brand",
            "criteria": "A product or branded packaging is visually present at any time in the video. Where the product is a service a relevant substitute should be shown such as via a branded app or branded service personnel.",
            "type": "full_video",
            "question": "Is any of the following products: {branded_products} or product categories: {branded_products_categories} visually present at any time in the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Provide the exact timestamp when the products {branded_products} or product categories: {branded_products_categories} are visually present.",
                "Return True if and only if the branded products or product categories are visually present in the video.",
            ],
            "mode": "agentic",
            "tool_group": "visual",
        },
        {
            "id": "b_product_visuals_1st_5_secs",
            "name": "Product Visuals (First 5 seconds)",
            "category": "Brand",
            "criteria": "A product or branded packaging is visually present in the first 5 seconds of the video. Where the product is a service a relevant substitute should be shown such as via a branded app or branded service personnel.",
            "type": "first_5_secs_video",
            "question": "Is any of the following products: {branded_products} or product categories: {branded_products_categories} visually present in the first 5 seconds of the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "IMPORTANT: Only analyse visual data from the first 5 seconds of the video.",
                "Provide the exact timestamp when the products {branded_products} or product categories: {branded_products_categories} are visually present.",
                "Return True if and only if the branded products or product categories are visually present in the first 5 seconds.",
            ],
            "mode": "agentic",
            "tool_group": "visual",
        },
        {
            "id": "c_overall_pacing",
            "name": "Overall Pacing",
            "category": "Connect",
            "criteria": "The pace of the video is greater than 2 seconds per shot/frame.",
            "type": "full_video",
            "question": "Is the pace of video greater than 2 seconds per shot/frame?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Query the extracted video data using the provided tools to answer the question.",
                "Return True if and only if the pace of video greater than 2 seconds per shot/frame.",
            ],
            "mode": "baseline",
            "tool_group": None,
        },
        {
            "id": "c_presence_of_people",
            "name": "Presence of People",
            "category": "Connect",
            "criteria": "People are shown in any capacity at any time in the video. Any human body parts are acceptable to pass this guideline. Alternate representations of people such as Animations or Cartoons ARE acceptable.",
            "type": "full_video",
            "question": "Are there people present at any time in the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Query the extracted video data using the provided tools to answer the question.",
                "Provide the exact timestamp when people are present in the video.",
            ],
            "mode": "agentic",
            "tool_group": "visual",
        },
        {
            "id": "c_presence_of_people_1st_5_secs",
            "name": "Presence of People (First 5 seconds)",
            "category": "Connect",
            "criteria": "People are shown in any capacity in the first 5 seconds of the video. Any human body parts are acceptable to pass this guideline. Alternate representations of people such as Animations or Cartoons ARE acceptable.",
            "type": "first_5_secs_video",
            "question": "Are there people present in the first 5 seconds of the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "IMPORTANT: Only analyse visual data from the first 5 seconds of the video.",
                "Provide the exact timestamp when people are present.",
            ],
            "mode": "agentic",
            "tool_group": "visual",
        },
        {
            "id": "c_visible_face",
            "name": "Visible Face (First 5 seconds)",
            "category": "Connect",
            "criteria": "At least one human face is present in the first 5 seconds of the video. Alternate representations of people such as Animations or Cartoons ARE acceptable.",
            "type": "first_5_secs_video",
            "question": "Is there a human face present in the first 5 seconds of the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "IMPORTANT: Only analyse visual data from the first 5 seconds of the video.",
                "Provide the exact timestamp when the human face is present.",
            ],
            "mode": "agentic",
            "tool_group": "visual",
        },
        {
            "id": "c_visible_face_close_up",
            "name": "Visible Face (Close Up)",
            "category": "Connect",
            "criteria": "There is a close up of a human face at any time in the video.",
            "type": "full_video",
            "question": "Is there a close up of a human face present at any time the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Query the extracted video data using the provided tools to answer the question.",
                "Provide the exact timestamp when there is a close up of a human face.",
            ],
            "mode": "agentic",
            "tool_group": "visual",
        },
        {
            "id": "d_audio_speech_early_1st_5_secs",
            "name": "Audio Early (First 5 seconds)",
            "category": "Direct",
            "criteria": "Speech is detected in the audio of the video.",
            "type": "first_5_secs_video",
            "question": "Is speech detected in the audio of the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Only strictly use the speech of the video to answer.",
            ],
            "mode": "baseline",
            "tool_group": None,
        },
        {
            "id": "d_call_to_action_speech",
            "name": "Call To Action (Speech)",
            "category": "Direct",
            "criteria": "A 'Call To Action' phrase is heard or mentioned in the audio or speech at any time in the video.",
            "type": "full_video",
            "question": "Is any call to action heard or mentioned in the speech of the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Some examples of call to actions are: {call_to_actions}",
                "Provide the exact timestamp when the call to actions are heard or mentioned in the speech of the video.",
            ],
            "mode": "agentic",
            "tool_group": "audio",
        },
        {
            "id": "d_call_to_action_text",
            "name": "Call To Action (Text)",
            "category": "Direct",
            "criteria": "A 'Call To Action' phrase is detected in the video supers (overlaid text) at any time in the video.",
            "type": "full_video",
            "question": "Is any call to action detected in any text overlay at any time in the video?",
            "instructions": [
                "Consider the following criteria for your answer: {criteria}",
                "Some examples of call to actions are: {call_to_actions}",
                "Query the extracted video data using the provided tools to answer the question.",
                "Provide the exact timestamp when the call to action is detected in any text overlay in the video.",
            ],
            "mode": "agentic",
            "tool_group": "text",
        },
    ]

    return feature_configs
