/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List platforms */
        get: operations["list_platforms_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read-only config defaults
         * @description Return the current ``clip_scribe.yaml`` as-is so the form can pre-populate.
         */
        get: operations["get_defaults_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List input videos */
        get: operations["list_inputs_inputs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /** Create and enqueue a job */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete a completed, failed, or canceled job */
        delete: operations["delete_job_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live job progress (SSE)
         * @description Stream a job's progress + log events as Server-Sent Events.
         */
        get: operations["job_events_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coarse live progress (for the jobs list bar)
         * @description One-shot progress percent from the job's Redis stream (no SSE).
         *
         *     Cheap enough to poll per running row: reads the stream once and reduces it.
         *     A completed job reports 100 without touching Redis; if the stream is gone or
         *     Redis is down, percent falls back to 0 (or 100 when already completed).
         */
        get: operations["job_progress_jobs__job_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a queued job */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a failed or canceled job */
        post: operations["retry_job_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/global-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global stats + shot boundaries */
        get: operations["get_global_stats_runs__run_id__global_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visual object occurrences */
        get: operations["get_objects_runs__run_id__objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/text-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OCR text events */
        get: operations["get_text_events_runs__run_id__text_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/audio-segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audio transcript segments */
        get: operations["get_audio_segments_runs__run_id__audio_segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scene descriptions */
        get: operations["get_scenes_runs__run_id__scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Raw frame detections (overlay) */
        get: operations["get_frames_runs__run_id__frames_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/parser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parser results */
        get: operations["get_parser_runs__run_id__parser_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask the advisory agent (SSE stream) */
        post: operations["post_chat_runs__run_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List advisory-chat sessions for a run */
        get: operations["list_sessions_runs__run_id__chat_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/chat/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one chat session's transcript */
        get: operations["get_session_runs__run_id__chat__session_id__get"];
        put?: never;
        post?: never;
        /** Delete a chat session */
        delete: operations["delete_session_runs__run_id__chat__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload video(s) */
        post: operations["upload_videos_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Original input video (Range-aware) */
        get: operations["get_video_runs__run_id__video_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/tracked-video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tracked output mp4 (Range-aware) */
        get: operations["get_tracked_video_runs__run_id__tracked_video_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/png/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visualization PNG */
        get: operations["get_png_runs__run_id__png__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AudioSegment
         * @description Whisper transcript segment.
         */
        AudioSegment: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /** Start Time */
            start_time?: number | null;
            /** End Time */
            end_time?: number | null;
            /** Text */
            text?: string | null;
            /** Confidence */
            confidence?: number | null;
        };
        /** Body_upload_videos_uploads_post */
        Body_upload_videos_uploads_post: {
            /** Files */
            files: string[];
        };
        /** ChatHistoryResponse */
        ChatHistoryResponse: {
            /** Run Id */
            run_id: string;
            /** Session Id */
            session_id: string;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /**
         * ChatMessage
         * @description One persisted transcript message.
         */
        ChatMessage: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Tool Calls Json */
            tool_calls_json?: string[] | null;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * ChatRequest
         * @description One user turn in an advisory-chat session.
         */
        ChatRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id?: string | null;
        };
        /**
         * ChatSession
         * @description Summary of one chat session for the run's session list.
         */
        ChatSession: {
            /** Session Id */
            session_id: string;
            /** Message Count */
            message_count: number;
            /** Title */
            title?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Last At */
            last_at?: string | null;
        };
        /** ChatSessionsResponse */
        ChatSessionsResponse: {
            /** Run Id */
            run_id: string;
            /** Sessions */
            sessions: components["schemas"]["ChatSession"][];
        };
        /**
         * FrameDetection
         * @description A single bounding-box detection in one video frame.
         */
        FrameDetection: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /** Shot Index */
            shot_index?: number | null;
            /** Frame Idx */
            frame_idx?: number | null;
            /** Timestamp Sec */
            timestamp_sec?: number | null;
            /** Source */
            source?: string | null;
            /** Label */
            label?: string | null;
            /** Text */
            text?: string | null;
            /** Box X1 */
            box_x1?: number | null;
            /** Box Y1 */
            box_y1?: number | null;
            /** Box X2 */
            box_x2?: number | null;
            /** Box Y2 */
            box_y2?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Object Id */
            object_id?: number | null;
        };
        /**
         * GlobalStatsResponse
         * @description Combined global stats + shot boundary list for a run.
         */
        GlobalStatsResponse: {
            /** Global Stats */
            global_stats?: {
                [key: string]: unknown;
            } | null;
            /** Shot Boundaries */
            shot_boundaries: components["schemas"]["ShotBoundary"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InputVideo */
        InputVideo: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** InputsResponse */
        InputsResponse: {
            /** Videos */
            videos: components["schemas"]["InputVideo"][];
        };
        /**
         * JobCreateRequest
         * @description Create + enqueue a job. Mirrors the ``main.py`` params, minus device.
         *
         *     Device is not user-settable: the app uses the config value (the CLI uses
         *     ``--device``). Video is referenced by a server-side path under ``INPUT_DIR``
         *     (populated via ``POST /uploads`` or already present in ``input/``).
         *
         *     ``platform`` selects the evaluation platform; ``platform_params`` is a raw
         *     object validated against the selected platform's schema (see
         *     ``PLATFORM_PARAMS_MODELS``). The validated model is exposed via
         *     ``resolved_params``.
         */
        JobCreateRequest: {
            mode: components["schemas"]["JobMode"];
            /** @default youtube */
            platform: components["schemas"]["PlatformName"];
            /** Video Path */
            video_path?: string | null;
            /** Video Name */
            video_name?: string | null;
            /** Video Type */
            video_type?: string | null;
            /** Platform Params */
            platform_params?: {
                [key: string]: unknown;
            };
            /** User Hints */
            user_hints?: string[] | null;
            /**
             * Generate Hint From Name
             * @default false
             */
            generate_hint_from_name: boolean;
            /** Run Id */
            run_id?: string | null;
        };
        /**
         * JobCreatedResponse
         * @description 202 body for a freshly enqueued job.
         */
        JobCreatedResponse: {
            /** Job Id */
            job_id: string;
            /** Run Id */
            run_id: string | null;
            status: components["schemas"]["JobStatus"];
        };
        /** JobListResponse */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * JobMode
         * @enum {string}
         */
        JobMode: "full" | "extract" | "parse";
        /**
         * JobProgressResponse
         * @description Coarse live progress for a job, derived from its Redis event stream.
         *
         *     Feeds the jobs-list progress bar without a live SSE connection per row.
         *     ``percent`` is 0-100; the shot fields are null until shot processing starts.
         */
        JobProgressResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Percent */
            percent: number;
            /** Phase */
            phase?: string | null;
            /** Shots Done */
            shots_done?: number | null;
            /** Total Shots */
            total_shots?: number | null;
        };
        /**
         * JobResponse
         * @description Full orchestration state of a job.
         */
        JobResponse: {
            /** Job Id */
            job_id: string;
            /** Run Id */
            run_id?: string | null;
            /** Status */
            status: string;
            /** Mode */
            mode?: string | null;
            /** Video Name */
            video_name?: string | null;
            /** Video Path */
            video_path?: string | null;
            /** Video Type */
            video_type?: string | null;
            /** Device */
            device?: string | null;
            /** Platform */
            platform?: string | null;
            /** Error Text */
            error_text?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "completed" | "failed" | "canceled";
        /**
         * ParserResult
         * @description Persisted per-criterion evaluation from the parser.
         */
        ParserResult: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /** Platform */
            platform?: string | null;
            /** Feature Category */
            feature_category?: string | null;
            /** Feature Name */
            feature_name?: string | null;
            /** Feature Criteria */
            feature_criteria?: string | null;
            /** Evaluation */
            evaluation?: boolean | null;
            /** Llm Prompt */
            llm_prompt?: string | null;
            /** Llm Explanation */
            llm_explanation?: string | null;
            /** Langsmith Run Id */
            langsmith_run_id?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** PlatformInfo */
        PlatformInfo: {
            /** Name */
            name: string;
            /** Params */
            params: components["schemas"]["PlatformParamField"][];
        };
        /**
         * PlatformName
         * @description Supported evaluation platforms.
         *
         *     Adding a platform = a new member here, a ``BasePlatformParams`` subclass,
         *     and an entry in ``PLATFORM_PARAMS_MODELS``. Requests for any value not in
         *     this enum are rejected at validation (422) — non-YouTube is blocked today.
         * @enum {string}
         */
        PlatformName: "youtube";
        /** PlatformParamField */
        PlatformParamField: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Required */
            required: boolean;
            /** Description */
            description: string;
        };
        /** PlatformsResponse */
        PlatformsResponse: {
            /** Platforms */
            platforms: components["schemas"]["PlatformInfo"][];
        };
        /**
         * RunResponse
         * @description A completed extraction run.
         */
        RunResponse: {
            /** Run Id */
            run_id: string;
            /** Video Name */
            video_name?: string | null;
            /** Video Path */
            video_path?: string | null;
            /** Video Type */
            video_type?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * ShotBoundary
         * @description Temporal extent of a single shot.
         */
        ShotBoundary: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /** Shot Index */
            shot_index?: number | null;
            /** Start Sec */
            start_sec?: number | null;
            /** End Sec */
            end_sec?: number | null;
            /** Duration Sec */
            duration_sec?: number | null;
        };
        /**
         * TextEvent
         * @description OCR text event at a specific second.
         */
        TextEvent: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /** Second */
            second?: number | null;
            /** Line Index */
            line_index?: number | null;
            /** Text */
            text?: string | null;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Uploaded */
            uploaded: components["schemas"]["UploadedVideo"][];
        };
        /** UploadedVideo */
        UploadedVideo: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_platforms_platforms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformsResponse"];
                };
            };
        };
    };
    get_defaults_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_inputs_inputs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InputsResponse"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_progress_jobs__job_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_global_stats_runs__run_id__global_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_objects_runs__run_id__objects_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_text_events_runs__run_id__text_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audio_segments_runs__run_id__audio_segments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioSegment"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenes_runs__run_id__scenes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frames_runs__run_id__frames_get: {
        parameters: {
            query?: {
                from?: number | null;
                to?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameDetection"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_parser_runs__run_id__parser_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_runs__run_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_runs__run_id__chat_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_runs__run_id__chat__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_runs__run_id__chat__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_videos_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_videos_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_runs__run_id__video_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tracked_video_runs__run_id__tracked_video_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_png_runs__run_id__png__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
