"""add jobs, frame_detections, parser_results, shot_boundaries

Revision ID: 5b7769f8e6fd
Revises: 848b1a5f7886
Create Date: 2026-06-29 18:43:44.882745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b7769f8e6fd"
down_revision: Union[str, Sequence[str], None] = "848b1a5f7886"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "frame_detections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("shot_index", sa.Integer(), nullable=True),
        sa.Column("frame_idx", sa.Integer(), nullable=True),
        sa.Column("timestamp_sec", sa.Float(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("box_x1", sa.Float(), nullable=True),
        sa.Column("box_y1", sa.Float(), nullable=True),
        sa.Column("box_x2", sa.Float(), nullable=True),
        sa.Column("box_y2", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("object_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("frame_detections", schema=None) as batch_op:
        batch_op.create_index(
            "ix_frame_detections_run_frame", ["run_id", "frame_idx"], unique=False
        )
        batch_op.create_index(
            "ix_frame_detections_run_object", ["run_id", "object_id"], unique=False
        )

    op.create_table(
        "jobs",
        sa.Column("job_id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'queued'"), nullable=False
        ),
        sa.Column("celery_task_id", sa.Text(), nullable=True),
        sa.Column("mode", sa.Text(), nullable=True),
        sa.Column("video_name", sa.Text(), nullable=True),
        sa.Column("video_path", sa.Text(), nullable=True),
        sa.Column("video_type", sa.Text(), nullable=True),
        sa.Column("device", sa.Text(), nullable=True),
        sa.Column("platform", sa.Text(), nullable=True),
        sa.Column("params_json", sa.JSON(), nullable=True),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.Text(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("started_at", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "parser_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("platform", sa.Text(), nullable=True),
        sa.Column("feature_category", sa.Text(), nullable=True),
        sa.Column("feature_name", sa.Text(), nullable=True),
        sa.Column("feature_criteria", sa.Text(), nullable=True),
        sa.Column("evaluation", sa.Boolean(), nullable=True),
        sa.Column("llm_prompt", sa.Text(), nullable=True),
        sa.Column("llm_explanation", sa.Text(), nullable=True),
        sa.Column("langsmith_run_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.Text(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shot_boundaries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("shot_index", sa.Integer(), nullable=True),
        sa.Column("start_sec", sa.Float(), nullable=True),
        sa.Column("end_sec", sa.Float(), nullable=True),
        sa.Column("duration_sec", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shot_boundaries")
    op.drop_table("parser_results")
    op.drop_table("jobs")
    with op.batch_alter_table("frame_detections", schema=None) as batch_op:
        batch_op.drop_index("ix_frame_detections_run_object")
        batch_op.drop_index("ix_frame_detections_run_frame")

    op.drop_table("frame_detections")
    # ### end Alembic commands ###
