"""baseline existing schema

Revision ID: 848b1a5f7886
Revises:
Create Date: 2026-06-29 18:43:16.315112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "848b1a5f7886"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_segments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=True),
        sa.Column("end_time", sa.Float(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_table(
        "field_descriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("table_name", sa.Text(), nullable=False),
        sa.Column("column_name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("table_name", "column_name"),
        if_not_exists=True,
    )
    op.create_table(
        "global_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("total_shots", sa.Integer(), nullable=True),
        sa.Column("video_duration", sa.Float(), nullable=True),
        sa.Column("avg_shot_duration", sa.Float(), nullable=True),
        sa.Column("dynamic_start_detected", sa.Integer(), nullable=True),
        sa.Column("dynamic_start_first_shot_dur", sa.Float(), nullable=True),
        sa.Column("dynamic_start_criteria", sa.Text(), nullable=True),
        sa.Column("qp_intro_detected", sa.Integer(), nullable=True),
        sa.Column("qp_intro_shot_count", sa.Integer(), nullable=True),
        sa.Column("qp_intro_shots", sa.Text(), nullable=True),
        sa.Column("qp_intro_criteria", sa.Text(), nullable=True),
        sa.Column("qp_general_detected", sa.Integer(), nullable=True),
        sa.Column("qp_general_rapid_fire_segments", sa.Text(), nullable=True),
        sa.Column("qp_general_criteria", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_table(
        "runs",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("video_name", sa.Text(), nullable=True),
        sa.Column("video_path", sa.Text(), nullable=True),
        sa.Column("video_type", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.Text(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("run_id"),
        if_not_exists=True,
    )
    op.create_table(
        "scene_descriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("shot_index", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=True),
        sa.Column("end_time", sa.Float(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_table(
        "text_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("second", sa.Integer(), nullable=True),
        sa.Column("line_index", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_table(
        "visual_object_occurrences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("global_id", sa.Integer(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("shot_index", sa.Integer(), nullable=True),
        sa.Column("lifespan_start", sa.Float(), nullable=True),
        sa.Column("lifespan_end", sa.Float(), nullable=True),
        sa.Column("screen_coverage", sa.Float(), nullable=True),
        sa.Column("velocity_px_sec", sa.Float(), nullable=True),
        sa.Column("growth_factor", sa.Float(), nullable=True),
        sa.Column("direction", sa.Text(), nullable=True),
        sa.Column("centrality_score", sa.Float(), nullable=True),
        sa.Column("screen_time_ratio", sa.Float(), nullable=True),
        sa.Column("quadrant", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visual_object_occurrences")
    op.drop_table("text_events")
    op.drop_table("scene_descriptions")
    op.drop_table("runs")
    op.drop_table("global_stats")
    op.drop_table("field_descriptions")
    op.drop_table("audio_segments")
    # ### end Alembic commands ###
