import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

// Generated by the TanStack Router Vite plugin from src/routes/**.
// It won't exist until the first `pnpm dev` (or `pnpm build`) run — your editor
// may show a red squiggle here until then. That's expected; the plugin writes it.
import { routeTree } from "./routeTree.gen";
import "./styles.css";

// --- TanStack Query: the server-state cache ---
// Query owns everything that lives on the server (jobs, runs, etc). It handles
// caching, background refetching, loading/error states, and dedupes identical
// requests. We create ONE client for the whole app and provide it via context.
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      // Data is considered "fresh" for 10s; within that window Query serves the
      // cache without refetching. Tune per-query later (a live job wants 0).
      staleTime: 10_000,
      retry: 1,
    },
  },
});

// --- TanStack Router: the typed router ---
// We hand it the generated route tree and put the query client in the router's
// `context`, so route loaders can prefetch data with the same cache the
// components use.
const router = createRouter({
  routeTree,
  context: { queryClient },
  // Show this while a route's data is loading, and scroll to top on navigation.
  defaultPreload: "intent",
});

// --- Module augmentation: how the router becomes fully type-safe ---
// This `declare module` block merges OUR router's type into the library's
// `Register` interface. After this, every <Link to="...">, useParams(), and
// navigate() call is checked against the ACTUAL routes we defined — a typo like
// to="/jbs" becomes a compile error, and params are typed per-route. This is the
// single most important line for the "typed routing" experience.
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const rootEl = document.getElementById("root");
if (!rootEl) throw new Error("#root not found in index.html");

createRoot(rootEl).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
);
